# Generated by Django 3.1.5 on 2021-11-19 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Address', models.CharField(max_length=100, null=True)),
                ('segment', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('Area', models.CharField(max_length=100, null=True)),
                ('Status', models.CharField(max_length=100, null=True)),
                ('hoster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrentalApp.registered')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrentalApp.registered')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquirer_email', models.CharField(max_length=100, null=True)),
                ('enquiry_msg', models.CharField(max_length=100, null=True)),
                ('enquirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrentalApp.registered')),
            ],
        ),
    ]
